# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d891915c6126864b46ce2c38ffc7292333bdef949aa4c6dfe641199130f8494cddff92a80cf15b147a8a614062d07d766084ce154117ff7dd43ddbcbbbb0bfd4

test:
  secret_key_base: 7f3f352a04533bdf8f6e20fd9794ab3863a922a30368d91fb1f760c6632073d279232596d2703baf96e3914f316e44444f3666c1237b85193caab855b18ec2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
